### PR TITLE
Update README to include working main fn

### PR DESCRIPTION
**Pull request by nixpulvis**
Similar to #32 and https://gist.github.com/KarelPeeters/74a864d42af4b1be5f8d8b4a5aed675d, I too was trying to run the example in the README, which needed a little more to it. This PR works on my Intel OpenCL platform and I can test on AMD later if needed.

If accepted, I'll indent the `main` function properly, I choose to leave it outdented for easier diff viewing.

### CODE REVIEW

**Comment by nixpulvis** [comment]
I'm actually wondering if moving the example to `examples/` would make things easier for everyone and make the README a bit more digestible?

**Review by kenba — APPROVED** [review]
Thank you. It'll be good to have a readme example that actually works! ;)

**Comment by kenba** [comment]
You have a good point about the size of the example now.

However, with regards to moving it to an `/examples` folder, I'd prefer to keep the example in the readme file for now.
It may be possible to make in appear smaller in crates.io using some doc comments.

I may copy it to an `/examples` folder later, especially when there are more examples. There are some in the Nvidia link that I think would make good examples of how to use the library.

**Comment by kenba** [comment]
When you have completed your draft please can you merge it into the `develop` branch, not `main` thank you.

**Comment by nixpulvis** [comment]
@kenba working on cleaning a few things up right now and I had a question: Shouldn't [`get_devices`](https://docs.rs/opencl3/0.5.0/opencl3/platform/struct.Platform.html#method.get_devices) return `Result<Vec<Device>>` instead of ` Result<Vec<cl_device_id>>`? This would match the similar [`get_platforms`](https://docs.rs/opencl3/0.5.0/opencl3/platform/fn.get_platforms.html) function.

This would clean up the following bit of code:

```rust
    let platform = opencl3::platform::get_platforms()?.pop()
        .expect("no OpenCL platforms");
    let device = platform.get_devices(CL_DEVICE_TYPE_GPU)?.pop()
        .expect("no device found in platform");
    let device = Device::new(device);
```

**Comment by nixpulvis** [comment]
OK, I think I'm pretty happy with this code now. If you'd like me to sway the README and SVM example's locations, just let me know. I put the shorter and simpler one in the README for my own personal preference.

Also, I'm curious if there's a nice way to extract the `` ```rust`` example into a `cargo run --example README`? Perhaps there's a way with a `build.rs` I could look into a bit later.

**Comment by nixpulvis** [comment]
Opened budziq/rust-skeptic#129.

**Review by kenba — COMMENTED** [review]
This is *not* the PR that I approved!

**Comment by kenba** [comment]
Nathan, first and foremost I want to thank you for submitting a pull request to help improve this library.  
I was very happy with your initial pull request. If you hadn’t marked it as draft, I would have merged it back then.

However, instead of just indenting the example and merging it into the `develop` branch, you have now submitted a completely different change! I don’t know whether you are a professional developer, or not.  However, where I work, we are expected to *only* resolve PR review comments, *not* dramatically change our original PR submission. In future, please just do what you say you will.

Unfortunately, I don’t agree with your latest changes:
- Why did you change the example? I’m very happy with the `inclusive_scan_int` example, it shows how to use OpenCL 2 features in a kernel. I couldn’t care less about `vector_add`!
- I completely understand why you would want to include the `skeptic` library to verify the readme example, especially after my mistake with the `&`. However, I’d prefer to keep the number of dependencies of this library to a minimum (even `serde` is included as optional). So, including a library *just* to verify the readme example seems overkill to me. Especially when that library itself has 7 dependencies.

With regards to your questions:
- `get-devices` returns a ` Result<Vec<cl_device_id>>` because `Context::new` takes a ` &[cl_device_id]`. I agree that it would be nice if it matched `get_platforms`, but adding the line `let device = Device::new(device);` is much nicer than having to get all the device ids out of a `&[Device]` in `Context::new`...
- “I'm also curious if this crate would consider helper functions for finding devices across platforms to be in scope.”  Yes, I’d be interested to see your ideas for helper functions. Please feel free to submit them in a new PR.
- “Also, I'm curious if there's a nice way to extract the `rust` example into a cargo run --example README?”. Please only do this for your own curiosity. I’d prefer to provide the readme example as an example in a new examples directory, and just cut and past the relevant code into the `README.md` file.

When considering any future changes please bear in mind that the library now has over 2,500 downloads and is currently averaging over 50 downloads a day. So, I'm now reluctant to make major changes to the existing API unless they are likely to provide a significant benefit to the current users whose code they are likely to break!

**Comment by nixpulvis** [comment]
> So, including a library just to verify the readme example seems overkill to me.

I completely agree and plan to write an extremely small `build.rs` which does only what we need. People may still be freaked out by the `build.rs`, but I don't know how to please everyone.

**Comment by nixpulvis** [comment]
> I couldn’t care less about `vector_add`!

I might still be having trouble understanding some of OpenCL 3.0, but given that OpenCL 2.0 features are now *optional*, wouldn't it make more sense to use a different example for a project named `opencl3`? See the relevent passage from the spec below:

> OpenCL 3.0 is designed to enable any OpenCL implementation supporting OpenCL 1.2 or newer to easily support and transition to OpenCL 3.0, by making many features in OpenCL 2.0, 2.1, or 2.2  optional. This means that OpenCL 3.0 is backwards compatible  with OpenCL 1.2, but is not necessarily backwards compatible with OpenCL 2.0, 2.1, or 2.2.

I understand that I changed things a good bit between "draft" stage and "review" (sorry, the draft feature is still a bit new to me too), but I promise I only did so because your initial response seemed welcoming and open to discussion. Frankly, I was quite shocked when I saw your email pop up while I was out for a walk.

> If you hadn’t marked it as draft, I would have merged it back then.

Nothing is stopping you, 19537a339b110d8f06977efd9698bdb70af76068 still contains the original 20 line delta. I might have as well, however I don't have the permissions on your repository as you implied here: https://github.com/kenba/opencl3/pull/36#issuecomment-919459521.

I'm sorry if I'm pushing you a bit, but please don't come after my "professionalism" again. I'm just trying to help you out.

**Comment by kenba** [comment]
> Nathan, first and foremost I want to thank you for submitting a pull request to help improve this library.

I mean it. It is a great help to have developers provide PRs to fix issues with the library. However, I appreciate that you may not have been aware of the usual issue or PR process. There is now a [Contributing](https://github.com/kenba/opencl3/blob/main/CONTRIBUTING.md) guide in the repo which should make the process clearer.

> Nothing is stopping you, 19537a3 still contains the original 20 line delta.

There is no point. I eventually fixed issue #32 by simply adding the `&`. This PR is now closed. I have no intention of re-opening it.

> “I'm also curious if this crate would consider helper functions for finding devices across platforms to be in scope.” Yes, I’d be interested to see your ideas for helper functions. Please feel free to submit them in a new PR.

So why not forget about this PR and consider raising a new PR with helper functions for finding devices across platforms?

**Comment by nixpulvis** [comment]
> a new PR with helper functions for finding devices across platforms?

OK, I'm actually in the process of setting up both an AMD and NVIDIA rig, however I'd need a new motherboard to really test them together. I might be able to hack something together regardless.

That said, what would be the right place to lay out designs and get feedback before I do a lot of testing (and rig building)? I tried to open a "draft" in this PR for roughly this purpose, but I take it that's not the right place. Would you like me to simply maintain an issue on the repo titled: "Platform / Device Discovery"?

As always, I'm also open to other ideas.

**Pull request closed without merging**
